<table width="100%" border="0" cellspacing="0" cellpadding="2" class="rhtbl">
  <tbody><tr>
    <th nowrap="" align="left"><?= $this->datatableOptions['editForm']['title'] ?></th>
  </tr>
  <tr>
    <td class="xpad"><table width="100%" border="0" cellspacing="0" cellpadding="2">
        <tbody><tr>
          <td><?= $this->form ?></td>
          </tr>
      </tbody></table></td>
  </tr>
</tbody></table>
